---
abstract: 'Generate POD documentation from Rinci function metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-To-POD
requires:
  Data::Dump: 0
  File::Which: 0
  Locale::Maketext::Lexicon::Gettext: 0
  Log::Any: 0
  Markdown::Pod: 0
  Moo: 0
  Perinci::Access: 0
  Perinci::CmdLine: 0.83
  Perinci::Sub::GetArgs::Argv: 0
  Perinci::Sub::To::FuncBase: 0.28
  Perinci::Sub::To::FuncBase::I18N: 0.28
  Perinci::Sub::To::FuncBase::I18N::en: 0.28
  Perinci::Sub::To::Text: 0.28
  Perinci::Sub::Util: 0
  perl: 5.010001
resources: {}
version: 0.08
